"""Step definitions for the typedef-drift feature (3 scenarios).

Binds every scenario in ``typedef_drift.feature`` and exercises
``knowledge.typedefs`` — ``generate_typedef_set``, ``write_typedef_set`` and
``check_typedef_drift`` — over a real on-disk generated set under ``tmp_path``.

RED leg: ``knowledge.typedefs`` does not yet exist, so its entry points are
imported inside the step bodies — each scenario fails on the absent behaviour,
not at collection time. The GREEN leg adds the module and makes all three pass.

The typedef under test is the ``pdr`` artifact type (its rules exercise the
richest template and schema fragment).
"""

from __future__ import annotations

from pathlib import Path

import pytest
from pytest_bdd import scenario, given, then, when

from knowledge.artifact_types import artifact_type

FEATURE = "typedef_drift.feature"
TYPEDEF_NAME = "pdr"


@pytest.fixture
def context() -> dict:
    return {}


@scenario(FEATURE, "a generated set that matches its typedef passes the drift check")
def test_clean_set_passes() -> None: ...


@scenario(FEATURE, "a hand-edited generated file is caught as drift and fails the check")
def test_hand_edit_caught() -> None: ...


@scenario(
    FEATURE,
    "regenerating over an unchanged typedef reproduces the generated set byte-for-byte",
)
def test_regeneration_byte_stable() -> None: ...


@given(
    "a typedef together with a template and schema fragment that were emitted "
    "from that typedef and are unchanged"
)
def _generated_unchanged(context: dict, tmp_path: Path) -> None:
    from knowledge.typedefs import write_typedef_set

    atype = artifact_type(TYPEDEF_NAME)
    result = write_typedef_set(atype, tmp_path)
    # The set was freshly emitted: every path was written.
    assert result.changed_count >= 2
    context["atype"] = atype
    context["out_dir"] = tmp_path


@given(
    "a typedef whose generated template or schema fragment has been hand-edited "
    "so it no longer matches what the typedef would emit"
)
def _hand_edited(context: dict, tmp_path: Path) -> None:
    from knowledge.typedefs import write_typedef_set

    atype = artifact_type(TYPEDEF_NAME)
    write_typedef_set(atype, tmp_path)
    # Hand-edit one generated file so its bytes no longer match the typedef.
    edited = tmp_path / "templates" / f"{TYPEDEF_NAME}.md"
    edited.write_bytes(edited.read_bytes() + b"\nhand-edited line not from the typedef\n")
    context["atype"] = atype
    context["out_dir"] = tmp_path
    context["edited_path"] = f"templates/{TYPEDEF_NAME}.md"


@given("a typedef whose template and schema fragment have already been generated")
def _already_generated(context: dict, tmp_path: Path) -> None:
    from knowledge.typedefs import generate_typedef_set, write_typedef_set

    atype = artifact_type(TYPEDEF_NAME)
    write_typedef_set(atype, tmp_path)
    # Capture the committed generated bytes for the byte-for-byte comparison.
    context["atype"] = atype
    context["out_dir"] = tmp_path
    context["committed"] = {
        rel: (tmp_path / rel).read_bytes() for rel in generate_typedef_set(atype)
    }


@when("the knowledge context runs the drift check over the typedef and its generated set")
def _run_drift_check(context: dict) -> None:
    from knowledge.typedefs import check_typedef_drift

    context["result"] = check_typedef_drift(context["atype"], context["out_dir"])


@when("the knowledge context regenerates the template and schema fragment from the unchanged typedef")
def _regenerate(context: dict) -> None:
    from knowledge.typedefs import write_typedef_set

    context["write_result"] = write_typedef_set(context["atype"], context["out_dir"])


@then("it reports no drift")
def _no_drift(context: dict) -> None:
    result = context["result"]
    assert result.has_drift is False
    assert result.drift == ()


@then("the check exits zero")
def _exits_zero(context: dict) -> None:
    assert context["result"].exit_code == 0


@then("it reports drift naming the generated file that no longer matches the typedef")
def _drift_names_file(context: dict) -> None:
    result = context["result"]
    assert result.has_drift is True
    assert context["edited_path"] in result.drift


@then("the check exits non-zero")
def _exits_non_zero(context: dict) -> None:
    assert context["result"].exit_code != 0


@then("the regenerated files are byte-for-byte identical to the committed generated set")
def _byte_identical(context: dict) -> None:
    out_dir = context["out_dir"]
    for rel, committed_bytes in context["committed"].items():
        assert (out_dir / rel).read_bytes() == committed_bytes


@then("the regeneration writes zero changed bytes")
def _zero_changed(context: dict) -> None:
    result = context["write_result"]
    assert result.changed_paths == ()
    assert result.changed_count == 0
