title: Product
version: 1
schema:
  allOf:
    - $ref: kb:schema/shop-artifact
  type: object
  properties:
    title:
      type: string
    gist:
      type: string
      maxLength: 200
      pattern: '^[^\n]*(?!\n)$'
  required: [title, gist]
  sections:
    - title: Purpose
  summary: [gist]
