"""The shopsystem-knowledge bounded context.

Discovery-first knowledge context: generate every projection tier (L0/L1/L2)
and both index entries deterministically from a single source decision
document whose YAML frontmatter is the only machine truth.
"""

from knowledge.adversarial import (
    AdversarialResult,
    Verdict,
    VerdictKind,
    run_adversarial_pass,
)
from knowledge.artifact_types import (
    ARTIFACT_TYPES,
    RECOGNIZED_ARTIFACT_TYPES,
    SHARED_REQUIRED_FIELDS,
    STORED_PROJECTION_FIELDS,
    Artifact,
    ArtifactType,
    artifact_type,
    parse_artifact,
)
from knowledge.discovery import (
    DiscoveryResult,
    DraftDecision,
    L0L1Index,
    L0L1IndexEntry,
    Neighbour,
    build_l0l1_index,
    run_authoring_discovery,
)
from knowledge.schema import (
    ConformanceResult,
    Diagnostic,
    SectionCheckResult,
    check_required_sections,
    validate_frontmatter,
)
from knowledge.typedefs import (
    TypedefDriftResult,
    TypedefWriteResult,
    check_typedef_drift,
    generate_all_typedefs,
    generate_typedef_set,
    render_schema_fragment,
    render_template,
    write_typedef_set,
)
from knowledge.projections import (
    ARCHITECTURE_DECISION_KIND,
    RECOGNIZED_DECISION_HEADINGS,
    CheckResult,
    KindProjections,
    KnowledgeContext,
    L0Card,
    L1Extract,
    ProjectionBundle,
    WriteResult,
    check_corpus,
    extract_decision_section,
    generate_corpus,
    generate_projections,
    parse_frontmatter,
    write_corpus,
)

__all__ = [
    "ARCHITECTURE_DECISION_KIND",
    "ARTIFACT_TYPES",
    "RECOGNIZED_ARTIFACT_TYPES",
    "RECOGNIZED_DECISION_HEADINGS",
    "SHARED_REQUIRED_FIELDS",
    "STORED_PROJECTION_FIELDS",
    "AdversarialResult",
    "Artifact",
    "ArtifactType",
    "CheckResult",
    "ConformanceResult",
    "Diagnostic",
    "DiscoveryResult",
    "DraftDecision",
    "KindProjections",
    "KnowledgeContext",
    "L0Card",
    "L0L1Index",
    "L0L1IndexEntry",
    "L1Extract",
    "Neighbour",
    "ProjectionBundle",
    "SectionCheckResult",
    "TypedefDriftResult",
    "TypedefWriteResult",
    "Verdict",
    "VerdictKind",
    "WriteResult",
    "artifact_type",
    "build_l0l1_index",
    "check_corpus",
    "check_required_sections",
    "check_typedef_drift",
    "extract_decision_section",
    "generate_all_typedefs",
    "generate_corpus",
    "generate_projections",
    "generate_typedef_set",
    "parse_artifact",
    "parse_frontmatter",
    "render_schema_fragment",
    "render_template",
    "run_adversarial_pass",
    "run_authoring_discovery",
    "validate_frontmatter",
    "write_corpus",
    "write_typedef_set",
]
