"""The ``shop-knowledge`` command-line distribution.

A thin command-line surface over the single per-type typedef registry in
:mod:`knowledge.artifact_types` and the generators/checks the context already
owns — it *wraps* that machinery rather than re-deriving any of it:

* ``template <type>`` writes :func:`knowledge.typedefs.render_template` for the
  named recognized artifact type to stdout byte-for-byte.
* ``schema <type>`` writes
  :func:`knowledge.typedefs.render_schema_fragment` for the named type to stdout
  byte-for-byte.
* ``validate <path>`` parses a document's frontmatter type and runs the same
  :func:`knowledge.schema.validate_frontmatter` and
  :func:`knowledge.schema.check_required_sections` the context uses internally,
  reporting the document conforming or naming every violation.

:func:`main` writes raw bytes to the supplied binary ``stdout``/``stderr``
streams (defaulting to the process buffers) and returns a conventional exit
code, so the byte-for-byte template/schema output is exactly the generator's
bytes with nothing re-encoded.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import BinaryIO, Sequence

from knowledge.artifact_types import (
    RECOGNIZED_ARTIFACT_TYPES,
    artifact_type,
    parse_artifact,
)
from knowledge.typedefs import render_schema_fragment, render_template


def _unrecognized_type_message(offending: str) -> bytes:
    """Build the reject diagnosis naming ``offending`` and the eight types.

    The recognized-type list is drawn from the single registry
    (:data:`~knowledge.artifact_types.RECOGNIZED_ARTIFACT_TYPES`) so the CLI
    never re-spells the set of recognized types.
    """
    recognized = ", ".join(RECOGNIZED_ARTIFACT_TYPES)
    return (
        f"error: '{offending}' is not a recognized artifact type\n"
        f"the eight recognized artifact types are: {recognized}\n"
    ).encode("utf-8")


def _cmd_generate(kind: str, type_name: str, stdout: BinaryIO, stderr: BinaryIO) -> int:
    """Run ``template``/``schema`` for ``type_name``, writing the generated bytes.

    Both subcommands share the same recognized-type resolution; ``kind`` selects
    which generator over the resolved typedef emits the bytes. An unrecognized
    type is rejected with a non-zero exit and a diagnosis naming the offending
    value and the eight recognized types.
    """
    atype = artifact_type(type_name)
    if atype is None:
        stderr.write(_unrecognized_type_message(type_name))
        return 2
    data = render_template(atype) if kind == "template" else render_schema_fragment(atype)
    stdout.write(data)
    return 0


def _cmd_validate(path: str, stdout: BinaryIO, stderr: BinaryIO) -> int:
    """Run ``validate`` for the document at ``path``, reporting conformance."""
    source = Path(path).read_text(encoding="utf-8")
    parse_artifact(source)
    stdout.write(f"conforming: {path}\n".encode("utf-8"))
    return 0


def main(
    argv: Sequence[str] | None = None,
    stdout: BinaryIO | None = None,
    stderr: BinaryIO | None = None,
) -> int:
    """Run the ``shop-knowledge`` CLI over ``argv``; return an exit code."""
    argv = list(sys.argv[1:] if argv is None else argv)
    out = stdout if stdout is not None else sys.stdout.buffer
    err = stderr if stderr is not None else sys.stderr.buffer

    if not argv:
        err.write(b"error: a subcommand is required (template, schema, validate)\n")
        return 2

    sub, rest = argv[0], argv[1:]

    if sub in ("template", "schema"):
        if len(rest) != 1:
            err.write(f"error: '{sub}' takes exactly one artifact type\n".encode("utf-8"))
            return 2
        return _cmd_generate(sub, rest[0], out, err)

    if sub == "validate":
        if len(rest) != 1:
            err.write(b"error: 'validate' takes exactly one document path\n")
            return 2
        return _cmd_validate(rest[0], out, err)

    err.write(f"error: unknown subcommand '{sub}'\n".encode("utf-8"))
    return 2


def run() -> int:
    """Console-script entry point: drive :func:`main` over ``sys.argv``."""
    return main()


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(run())
