"""The ``shop-knowledge`` command-line distribution.

A thin command-line surface over the single per-type typedef registry in
:mod:`knowledge.artifact_types` and the generators/checks the context already
owns — it *wraps* that machinery rather than re-deriving any of it:

* ``template <type>`` writes :func:`knowledge.typedefs.render_template` for the
  named recognized artifact type to stdout byte-for-byte.
* ``schema <type>`` writes
  :func:`knowledge.typedefs.render_schema_fragment` for the named type to stdout
  byte-for-byte.
* ``validate <path>`` parses a document's frontmatter type and runs the same
  :func:`knowledge.schema.validate_frontmatter` and
  :func:`knowledge.schema.check_required_sections` the context uses internally,
  reporting the document conforming or naming every violation.

:func:`main` writes raw bytes to the supplied binary ``stdout``/``stderr``
streams (defaulting to the process buffers) and returns a conventional exit
code, so the byte-for-byte template/schema output is exactly the generator's
bytes with nothing re-encoded.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import BinaryIO, Sequence

from knowledge.artifact_types import (
    RECOGNIZED_ARTIFACT_TYPES,
    artifact_type,
    parse_artifact,
)
from knowledge.schema import check_required_sections, validate_frontmatter
from knowledge.typedefs import render_schema_fragment, render_template


def _unrecognized_type_message(offending: str) -> bytes:
    """Build the reject diagnosis naming ``offending`` and the eight types.

    The recognized-type list is drawn from the single registry
    (:data:`~knowledge.artifact_types.RECOGNIZED_ARTIFACT_TYPES`) so the CLI
    never re-spells the set of recognized types.
    """
    recognized = ", ".join(RECOGNIZED_ARTIFACT_TYPES)
    return (
        f"error: '{offending}' is not a recognized artifact type\n"
        f"the eight recognized artifact types are: {recognized}\n"
    ).encode("utf-8")


def _cmd_generate(kind: str, type_name: str, stdout: BinaryIO, stderr: BinaryIO) -> int:
    """Run ``template``/``schema`` for ``type_name``, writing the generated bytes.

    Both subcommands share the same recognized-type resolution; ``kind`` selects
    which generator over the resolved typedef emits the bytes. An unrecognized
    type is rejected with a non-zero exit and a diagnosis naming the offending
    value and the eight recognized types.
    """
    atype = artifact_type(type_name)
    if atype is None:
        stderr.write(_unrecognized_type_message(type_name))
        return 2
    data = render_template(atype) if kind == "template" else render_schema_fragment(atype)
    stdout.write(data)
    return 0


def _cmd_validate(path: str, stdout: BinaryIO, stderr: BinaryIO) -> int:
    """Run ``validate`` for the document at ``path``, reporting conformance.

    The document is parsed and run through the context's own frontmatter check
    (:func:`knowledge.schema.validate_frontmatter`) and required-section check
    (:func:`knowledge.schema.check_required_sections`); every diagnosis they
    produce — a missing or unrecognized ``type``, a missing required field, a
    missing required section — is surfaced verbatim, so the CLI reports the same
    named diagnoses the internal checks do rather than re-deriving them. Both
    checks always run, so a document carrying more than one violation has every
    one reported rather than only the first.
    """
    source = Path(path).read_text(encoding="utf-8")
    artifact = parse_artifact(source)

    violations = list(validate_frontmatter(artifact).messages)
    violations += list(check_required_sections(artifact).messages)

    if not violations:
        stdout.write(f"conforming: {path}\n".encode("utf-8"))
        return 0

    lines = [f"non-conforming: {path}"] + [f"  - {message}" for message in violations]
    stdout.write(("\n".join(lines) + "\n").encode("utf-8"))
    return 1


def _cmd_navigate(
    doc_id: str,
    corpus_root: str,
    direction: str,
    stdout: BinaryIO,
    stderr: BinaryIO,
) -> int:
    """Run ``navigate`` for ``doc_id`` over the corpus rooted at ``corpus_root``.

    The document's edge-neighbourhood is read from *its own* materialized
    frontmatter link fields — the forward edges it declares and the back-edges
    materialized on it — and never by scanning the rest of the corpus for
    inbound edges, mirroring the :func:`~knowledge.typed_edges.resolve_referenced_by`
    frontmatter-only precedent. Each incident edge is listed as a link-field,
    target id, and resolved flag; a resolved target's id/type/status/title is
    surfaced as the edge's neighbour facets.

    The ``direction`` filter selects which half of the three reciprocity pairs
    the neighbourhood returns: ``both`` walks all :data:`LINK_FIELDS` (the full
    neighbourhood, unchanged), ``forward`` restricts to
    :data:`~knowledge.typed_edges.FORWARD_LINK_FIELDS`, and ``back`` restricts
    to :data:`~knowledge.typed_edges.BACK_LINK_FIELDS`. An edge whose target does
    not resolve is surfaced faithfully with ``resolved=false`` rather than
    dropped.

    An id absent from the corpus is a named error on stderr (naming the
    offending id and framing it as absent from the corpus) with a non-zero
    exit, rather than an empty answer.
    """
    from knowledge.corpus_loader import load_corpus
    from knowledge.typed_edges import (
        BACK_LINK_FIELDS,
        FORWARD_LINK_FIELDS,
        LINK_FIELDS,
        _link_targets,
    )

    if direction == "forward":
        walk_fields: tuple[str, ...] = FORWARD_LINK_FIELDS
    elif direction == "back":
        walk_fields = BACK_LINK_FIELDS
    else:
        walk_fields = LINK_FIELDS

    corpus = load_corpus(corpus_root)
    subject = corpus.get(doc_id)
    if subject is None:
        stderr.write(
            f"error: no document with id '{doc_id}' is present in the corpus\n".encode(
                "utf-8"
            )
        )
        return 2

    edges: list[dict[str, object]] = []
    for field_name in walk_fields:
        for target in _link_targets(subject, field_name):
            neighbour_art = corpus.get(target)
            resolved = neighbour_art is not None
            neighbour: dict[str, object] | None = None
            if neighbour_art is not None:
                neighbour = {
                    "id": neighbour_art.id,
                    "type": neighbour_art.type,
                    "status": neighbour_art.status,
                    "title": neighbour_art.title,
                }
            edges.append(
                {
                    "link_field": field_name,
                    "target": target,
                    "resolved": resolved,
                    "neighbour": neighbour,
                }
            )

    payload = {"id": doc_id, "edges": edges}
    stdout.write(json.dumps(payload).encode("utf-8"))
    return 0


def main(
    argv: Sequence[str] | None = None,
    stdout: BinaryIO | None = None,
    stderr: BinaryIO | None = None,
) -> int:
    """Run the ``shop-knowledge`` CLI over ``argv``; return an exit code."""
    argv = list(sys.argv[1:] if argv is None else argv)
    out = stdout if stdout is not None else sys.stdout.buffer
    err = stderr if stderr is not None else sys.stderr.buffer

    if not argv:
        err.write(
            b"error: a subcommand is required (template, schema, validate, navigate)\n"
        )
        return 2

    sub, rest = argv[0], argv[1:]

    if sub in ("template", "schema"):
        if len(rest) != 1:
            err.write(f"error: '{sub}' takes exactly one artifact type\n".encode("utf-8"))
            return 2
        return _cmd_generate(sub, rest[0], out, err)

    if sub == "validate":
        if len(rest) != 1:
            err.write(b"error: 'validate' takes exactly one document path\n")
            return 2
        return _cmd_validate(rest[0], out, err)

    if sub == "navigate":
        # navigate <doc_id> --corpus <root> [--direction forward|back|both]
        if len(rest) < 3 or rest[1] != "--corpus":
            err.write(
                b"error: 'navigate' takes a document id and --corpus <root>"
                b" (optionally --direction forward|back|both)\n"
            )
            return 2
        doc_id, corpus_root, extra = rest[0], rest[2], rest[3:]
        direction = "both"
        if extra:
            if len(extra) != 2 or extra[0] != "--direction":
                err.write(
                    b"error: 'navigate' accepts only --direction"
                    b" forward|back|both after --corpus <root>\n"
                )
                return 2
            direction = extra[1]
            if direction not in ("forward", "back", "both"):
                err.write(
                    f"error: unknown direction '{direction}'; expected one of "
                    f"forward, back, both\n".encode("utf-8")
                )
                return 2
        return _cmd_navigate(doc_id, corpus_root, direction, out, err)

    err.write(f"error: unknown subcommand '{sub}'\n".encode("utf-8"))
    return 2


def run() -> int:
    """Console-script entry point: drive :func:`main` over ``sys.argv``."""
    return main()


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(run())
